const description = "Waaxda Canshuuraha Guryaha/Daraha";

export const branches = [
    {
        name: "Afgoye",
        title: "Degmada Afgoye",
        code: "AFG",
        description: description,
        state: "Hirshabele State, Somalia",
        logo: '/images/afgoye.png',
    },
    {
        name: "Baidoa",
        code: "BAI",
        title: "Degamada Baidoa",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/baidoa.jpg',
    },
    {
        name: "Lafoole Area",
        code: "LAF",
        title: "Deganka Lafoole",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/lafoole.png',
    },
    {
        name: "Huddur",
        code: "HUD",
        title: "Degamada Huddur",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/huddur.jpg',
    },
    {
        name: "Diinsoor",
        code: "DIN",
        title: "Degamada Diinsoor",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/diinsoor.jpg',
    },
    {
        name: "Baraawe",
        code: "BAR",
        title: "Degamada Baraawe",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/baraawe.jpg',
    },
    {
        name: "Tawakal Area",
        code: "TAW",
        title: "Deganka Tawakal",
        description: description,
        state: "Southwest, Somalia",
        logo: '/images/tawakal.png',
    },
    {
        name: "Jowhar",
        code: "JOW",
        title: "Degmada Jowhar",
        description: description,
        state: "Hirshabele State, Somalia",
        logo: '/images/jowhar.png',
    },
];
